### ISSUE TITLE
Questions about the hyperparameter in Loss

### ISSUE THREAD

**Issue by PrinceRay7** [youngLBW/DiffusionGAN3D#1]
Thank you for your impressive work, I got a question about the loss hyperparameters which I didn't find in the supplementary part.
How large is the weighting coefficients lambda1 and lambda2 in Ldis and Ldiff losses respectively? Thank you!

**Comment by three-bee** [comment]
Did you get the weighing coefficients? I do not see them despite the issue having been closed.
